'\" t
.\"     Title: ansible-playbook
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/31/2018
.\"    Manual: System administration commands
.\"    Source: Ansible 2.5.4
.\"  Language: English
.\"
.TH "ANSIBLE\-PLAYBOOK" "1" "05/31/2018" "Ansible 2\&.5\&.4" "System administration commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ansible-playbook \- Runs Ansible playbooks, executing the defined tasks on the targeted hosts\&.
.SH "SYNOPSIS"
.sp
ansible\-playbook [options] playbook\&.yml [playbook2 \&...]
.SH "DESCRIPTION"
.sp
the tool to run \fBAnsible playbooks\fR, which are a configuration and multinode deployment system\&. See the project home page (https://docs\&.ansible\&.com) for more information\&.
.SH "COMMON OPTIONS"
.PP
\fB\-\-ask\-su\-pass\fR
.RS 4
ask for su password (deprecated, use become)
.RE
.PP
\fB\-\-ask\-sudo\-pass\fR
.RS 4
ask for sudo password (deprecated, use become)
.RE
.PP
\fB\-\-ask\-vault\-pass\fR
.RS 4
ask for vault password
.RE
.PP
\fB\-\-become\-method\fR \fIBECOME_METHOD\fR
.RS 4
privilege escalation method to use (default=sudo), valid choices: [ sudo | su | pbrun | pfexec | doas | dzdo | ksu | runas | pmrun | enable ]
.RE
.PP
\fB\-\-become\-user\fR \fIBECOME_USER\fR
.RS 4
run operations as this user (default=root)
.RE
.PP
\fB\-\-flush\-cache\fR
.RS 4
clear the fact cache for every host in inventory
.RE
.PP
\fB\-\-force\-handlers\fR
.RS 4
run handlers even if a task fails
.RE
.PP
\fB\-\-list\-hosts\fR
.RS 4
outputs a list of matching hosts; does not execute anything else
.RE
.PP
\fB\-\-list\-tags\fR
.RS 4
list all available tags
.RE
.PP
\fB\-\-list\-tasks\fR
.RS 4
list all tasks that would be executed
.RE
.PP
\fB\-\-private\-key\fR, \fB\-\-key\-file\fR
.RS 4
use this file to authenticate the connection
.RE
.PP
\fB\-\-scp\-extra\-args\fR \fISCP_EXTRA_ARGS\fR
.RS 4
specify extra arguments to pass to scp only (e\&.g\&. \-l)
.RE
.PP
\fB\-\-sftp\-extra\-args\fR \fISFTP_EXTRA_ARGS\fR
.RS 4
specify extra arguments to pass to sftp only (e\&.g\&. \-f, \-l)
.RE
.PP
\fB\-\-skip\-tags\fR
.RS 4
only run plays and tasks whose tags do not match these values
.RE
.PP
\fB\-\-ssh\-common\-args\fR \fISSH_COMMON_ARGS\fR
.RS 4
specify common arguments to pass to sftp/scp/ssh (e\&.g\&. ProxyCommand)
.RE
.PP
\fB\-\-ssh\-extra\-args\fR \fISSH_EXTRA_ARGS\fR
.RS 4
specify extra arguments to pass to ssh only (e\&.g\&. \-R)
.RE
.PP
\fB\-\-start\-at\-task\fR \fISTART_AT_TASK\fR
.RS 4
start the playbook at the task matching this name
.RE
.PP
\fB\-\-step\fR
.RS 4
one\-step\-at\-a\-time: confirm each task before running
.RE
.PP
\fB\-\-syntax\-check\fR
.RS 4
perform a syntax check on the playbook, but do not execute it
.RE
.PP
\fB\-\-vault\-id\fR
.RS 4
the vault identity to use
.RE
.PP
\fB\-\-vault\-password\-file\fR
.RS 4
vault password file
.RE
.PP
\fB\-\-version\fR
.RS 4
show program\(cqs version number and exit
.RE
.PP
\fB\-C\fR, \fB\-\-check\fR
.RS 4
don\(cqt make any changes; instead, try to predict some of the changes that may occur
.RE
.PP
\fB\-D\fR, \fB\-\-diff\fR
.RS 4
when changing (small) files and templates, show the differences in those files; works great with \-\-check
.RE
.PP
\fB\-K\fR, \fB\-\-ask\-become\-pass\fR
.RS 4
ask for privilege escalation password
.RE
.PP
\fB\-M\fR, \fB\-\-module\-path\fR
.RS 4
prepend colon\-separated path(s) to module library (default=[u\*(Aq/home/jenkins/\&.ansible/plugins/modules\*(Aq, u\*(Aq/usr/share/ansible/plugins/modules\*(Aq])
.RE
.PP
\fB\-R\fR \fISU_USER\fR, \fB\-\-su\-user\fR \fISU_USER\fR
.RS 4
run operations with su as this user (default=None) (deprecated, use become)
.RE
.PP
\fB\-S\fR, \fB\-\-su\fR
.RS 4
run operations with su (deprecated, use become)
.RE
.PP
\fB\-T\fR \fITIMEOUT\fR, \fB\-\-timeout\fR \fITIMEOUT\fR
.RS 4
override the connection timeout in seconds (default=10)
.RE
.PP
\fB\-U\fR \fISUDO_USER\fR, \fB\-\-sudo\-user\fR \fISUDO_USER\fR
.RS 4
desired sudo user (default=root) (deprecated, use become)
.RE
.PP
\fB\-b\fR, \fB\-\-become\fR
.RS 4
run operations with become (does not imply password prompting)
.RE
.PP
\fB\-c\fR \fICONNECTION\fR, \fB\-\-connection\fR \fICONNECTION\fR
.RS 4
connection type to use (default=smart)
.RE
.PP
\fB\-e\fR, \fB\-\-extra\-vars\fR
.RS 4
set additional variables as key=value or YAML/JSON, if filename prepend with @
.RE
.PP
\fB\-f\fR \fIFORKS\fR, \fB\-\-forks\fR \fIFORKS\fR
.RS 4
specify number of parallel processes to use (default=5)
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
show this help message and exit
.RE
.PP
\fB\-i\fR, \fB\-\-inventory\fR, \fB\-\-inventory\-file\fR
.RS 4
specify inventory host path or comma separated host list\&. \-\-inventory\-file is deprecated
.RE
.PP
\fB\-k\fR, \fB\-\-ask\-pass\fR
.RS 4
ask for connection password
.RE
.PP
\fB\-l\fR \fISUBSET\fR, \fB\-\-limit\fR \fISUBSET\fR
.RS 4
further limit selected hosts to an additional pattern
.RE
.PP
\fB\-s\fR, \fB\-\-sudo\fR
.RS 4
run operations with sudo (nopasswd) (deprecated, use become)
.RE
.PP
\fB\-t\fR, \fB\-\-tags\fR
.RS 4
only run plays and tasks tagged with these values
.RE
.PP
\fB\-u\fR \fIREMOTE_USER\fR, \fB\-\-user\fR \fIREMOTE_USER\fR
.RS 4
connect as this user (default=None)
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
verbose mode (\-vvv for more, \-vvvv to enable connection debugging)
.RE
.SH "ENVIRONMENT"
.sp
The following environment variables may be specified\&.
.sp
ANSIBLE_CONFIG \(em Override the default ansible config file
.sp
Many more are available for most options in ansible\&.cfg
.SH "FILES"
.sp
/etc/ansible/ansible\&.cfg \(em Config file, used if present
.sp
~/\&.ansible\&.cfg \(em User config file, overrides the default config if present
.SH "AUTHOR"
.sp
Ansible was originally written by Michael DeHaan\&.
.SH "COPYRIGHT"
.sp
Copyright \(co 2017 Red Hat, Inc | Ansible\&. Ansible is released under the terms of the GPLv3 License\&.
.SH "SEE ALSO"
.sp
\fBansible\fR(1), \fBansible\-config\fR(1), \fBansible\-console\fR(1), \fBansible\-doc\fR(1), \fBansible\-galaxy\fR(1), \fBansible\-inventory\fR(1), \fBansible\-pull\fR(1), \fBansible\-vault\fR(1)
.sp
Extensive documentation is available in the documentation site: http://docs\&.ansible\&.com\&. IRC and mailing list info can be found in file CONTRIBUTING\&.md, available in: https://github\&.com/ansible/ansible
