'\" t
.\"     Title: ansible-pull
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/31/2018
.\"    Manual: System administration commands
.\"    Source: Ansible 2.5.4
.\"  Language: English
.\"
.TH "ANSIBLE\-PULL" "1" "05/31/2018" "Ansible 2\&.5\&.4" "System administration commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ansible-pull \- pulls playbooks from a VCS repo and executes them for the local host
.SH "SYNOPSIS"
.sp
ansible\-pull \-U <repository> [options] [<playbook\&.yml>]
.SH "DESCRIPTION"
.sp
is used to up a remote copy of ansible on each managed node, each set to run via cron and update playbook source via a source repository\&. This inverts the default \fBpush\fR architecture of ansible into a \fBpull\fR architecture, which has near\-limitless scaling potential\&.
.sp
The setup playbook can be tuned to change the cron frequency, logging locations, and parameters to ansible\-pull\&. This is useful both for extreme scale\-out as well as periodic remediation\&. Usage of the \fIfetch\fR module to retrieve logs from ansible\-pull runs would be an excellent way to gather and analyze remote logs from ansible\-pull\&.
.SH "COMMON OPTIONS"
.PP
\fB\-\-accept\-host\-key\fR
.RS 4
adds the hostkey for the repo url if not already added
.RE
.PP
\fB\-\-ask\-su\-pass\fR
.RS 4
ask for su password (deprecated, use become)
.RE
.PP
\fB\-\-ask\-sudo\-pass\fR
.RS 4
ask for sudo password (deprecated, use become)
.RE
.PP
\fB\-\-ask\-vault\-pass\fR
.RS 4
ask for vault password
.RE
.PP
\fB\-\-check\fR
.RS 4
don\(cqt make any changes; instead, try to predict some of the changes that may occur
.RE
.PP
\fB\-\-clean\fR
.RS 4
modified files in the working repository will be discarded
.RE
.PP
\fB\-\-full\fR
.RS 4
Do a full clone, instead of a shallow one\&.
.RE
.PP
\fB\-\-list\-hosts\fR
.RS 4
outputs a list of matching hosts; does not execute anything else
.RE
.PP
\fB\-\-private\-key\fR, \fB\-\-key\-file\fR
.RS 4
use this file to authenticate the connection
.RE
.PP
\fB\-\-purge\fR
.RS 4
purge checkout after playbook run
.RE
.PP
\fB\-\-scp\-extra\-args\fR \fISCP_EXTRA_ARGS\fR
.RS 4
specify extra arguments to pass to scp only (e\&.g\&. \-l)
.RE
.PP
\fB\-\-sftp\-extra\-args\fR \fISFTP_EXTRA_ARGS\fR
.RS 4
specify extra arguments to pass to sftp only (e\&.g\&. \-f, \-l)
.RE
.PP
\fB\-\-skip\-tags\fR
.RS 4
only run plays and tasks whose tags do not match these values
.RE
.PP
\fB\-\-ssh\-common\-args\fR \fISSH_COMMON_ARGS\fR
.RS 4
specify common arguments to pass to sftp/scp/ssh (e\&.g\&. ProxyCommand)
.RE
.PP
\fB\-\-ssh\-extra\-args\fR \fISSH_EXTRA_ARGS\fR
.RS 4
specify extra arguments to pass to ssh only (e\&.g\&. \-R)
.RE
.PP
\fB\-\-track\-subs\fR
.RS 4
submodules will track the latest changes\&. This is equivalent to specifying the \-\-remote flag to git submodule update
.RE
.PP
\fB\-\-vault\-id\fR
.RS 4
the vault identity to use
.RE
.PP
\fB\-\-vault\-password\-file\fR
.RS 4
vault password file
.RE
.PP
\fB\-\-verify\-commit\fR
.RS 4
verify GPG signature of checked out commit, if it fails abort running the playbook\&. This needs the corresponding VCS module to support such an operation
.RE
.PP
\fB\-\-version\fR
.RS 4
show program\(cqs version number and exit
.RE
.PP
\fB\-C\fR \fICHECKOUT\fR, \fB\-\-checkout\fR \fICHECKOUT\fR
.RS 4
branch/tag/commit to checkout\&. Defaults to behavior of repository module\&.
.RE
.PP
\fB\-K\fR, \fB\-\-ask\-become\-pass\fR
.RS 4
ask for privilege escalation password
.RE
.PP
\fB\-M\fR, \fB\-\-module\-path\fR
.RS 4
prepend colon\-separated path(s) to module library (default=[u\*(Aq/home/jenkins/\&.ansible/plugins/modules\*(Aq, u\*(Aq/usr/share/ansible/plugins/modules\*(Aq])
.RE
.PP
\fB\-T\fR \fITIMEOUT\fR, \fB\-\-timeout\fR \fITIMEOUT\fR
.RS 4
override the connection timeout in seconds (default=10)
.RE
.PP
\fB\-U\fR \fIURL\fR, \fB\-\-url\fR \fIURL\fR
.RS 4
URL of the playbook repository
.RE
.PP
\fB\-c\fR \fICONNECTION\fR, \fB\-\-connection\fR \fICONNECTION\fR
.RS 4
connection type to use (default=smart)
.RE
.PP
\fB\-d\fR \fIDEST\fR, \fB\-\-directory\fR \fIDEST\fR
.RS 4
directory to checkout repository to
.RE
.PP
\fB\-e\fR, \fB\-\-extra\-vars\fR
.RS 4
set additional variables as key=value or YAML/JSON, if filename prepend with @
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
run the playbook even if the repository could not be updated
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
show this help message and exit
.RE
.PP
\fB\-i\fR, \fB\-\-inventory\fR, \fB\-\-inventory\-file\fR
.RS 4
specify inventory host path or comma separated host list\&. \-\-inventory\-file is deprecated
.RE
.PP
\fB\-k\fR, \fB\-\-ask\-pass\fR
.RS 4
ask for connection password
.RE
.PP
\fB\-l\fR \fISUBSET\fR, \fB\-\-limit\fR \fISUBSET\fR
.RS 4
further limit selected hosts to an additional pattern
.RE
.PP
\fB\-m\fR \fIMODULE_NAME\fR, \fB\-\-module\-name\fR \fIMODULE_NAME\fR
.RS 4
Repository module name, which ansible will use to check out the repo\&. Choices are (\fIgit\fR,
\fIsubversion\fR,
\fIhg\fR,
\fIbzr\fR)\&. Default is git\&.
.RE
.PP
\fB\-o\fR, \fB\-\-only\-if\-changed\fR
.RS 4
only run the playbook if the repository has been updated
.RE
.PP
\fB\-s\fR \fISLEEP\fR, \fB\-\-sleep\fR \fISLEEP\fR
.RS 4
sleep for random interval (between 0 and n number of seconds) before starting\&. This is a useful way to disperse git requests
.RE
.PP
\fB\-t\fR, \fB\-\-tags\fR
.RS 4
only run plays and tasks tagged with these values
.RE
.PP
\fB\-u\fR \fIREMOTE_USER\fR, \fB\-\-user\fR \fIREMOTE_USER\fR
.RS 4
connect as this user (default=None)
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
verbose mode (\-vvv for more, \-vvvv to enable connection debugging)
.RE
.SH "ENVIRONMENT"
.sp
The following environment variables may be specified\&.
.sp
ANSIBLE_CONFIG \(em Override the default ansible config file
.sp
Many more are available for most options in ansible\&.cfg
.SH "FILES"
.sp
/etc/ansible/ansible\&.cfg \(em Config file, used if present
.sp
~/\&.ansible\&.cfg \(em User config file, overrides the default config if present
.SH "AUTHOR"
.sp
Ansible was originally written by Michael DeHaan\&.
.SH "COPYRIGHT"
.sp
Copyright \(co 2017 Red Hat, Inc | Ansible\&. Ansible is released under the terms of the GPLv3 License\&.
.SH "SEE ALSO"
.sp
\fBansible\fR(1), \fBansible\-config\fR(1), \fBansible\-console\fR(1), \fBansible\-doc\fR(1), \fBansible\-galaxy\fR(1), \fBansible\-inventory\fR(1), \fBansible\-playbook\fR(1), \fBansible\-vault\fR(1)
.sp
Extensive documentation is available in the documentation site: http://docs\&.ansible\&.com\&. IRC and mailing list info can be found in file CONTRIBUTING\&.md, available in: https://github\&.com/ansible/ansible
